# langgraph_cognitive_arch/agent/graphs/brain.py
from typing import List
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import AIMessage
from pydantic import BaseModel, Field


from agent.state import AgentState, BrainThought
from agent.tools.brain_tools import (
    access_temp_knowledge, 
    access_permanent_knowledge, 
    write_to_permanent_knowledge
)

class GeneratedQuestions(BaseModel):
    """A list of questions generated by the Brain to clarify the task."""
    questions: List[str] = Field(description="A list of clarifying questions to break down the main task.")

# --- LLMs and Tools ---
brain_llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-pro",
    temperature=1,
    convert_system_message_to_human=True
)

brain_tools = [access_temp_knowledge, access_permanent_knowledge, write_to_permanent_knowledge]
brain_tool_node = ToolNode(brain_tools)

# --- Nodes for the Brain's Cognitive Loop ---

async def generate_node(state: AgentState) -> dict:
    """Step 1: GENERATE. Generates sub-questions to break down the task."""
    print("---BRAIN LOOP: Generate---")
    
    prompt = f"""
You are the 'Generate' component of a deep reasoning engine. 
Your task is to analyze the user's request and the conversation history, then generate a short list of internal questions that need to be answered to provide a complete solution.
If the previous step was a tool call, use its output to refine your next questions.

Conversation History:
{state['messages']}

Generated questions:
"""
    structured_llm = brain_llm.with_structured_output(GeneratedQuestions)
    response = await structured_llm.ainvoke(prompt)
    return {"generated_questions": response.questions}


async def think_node(state: AgentState) -> dict:
    """Step 2: THINK. Reviews the generated questions and decides on the next single action."""
    print("---BRAIN LOOP: Think---")
    
    prompt = f"""
You are the 'Think' component of a deep reasoning engine. Your task is to decide on the next single action to help answer the generated questions.

You have the following actions:
1.  `access_temp_knowledge`: Retrieve information from short-term memory.
2.  `access_permanent_knowledge`: Recall long-term memories.
3.  `write_to_permanent_knowledge`: Save a new insight to long-term memory.
4.  `respond_to_mind`: The questions have been fully answered. Formulate the final response.

Generated Questions:
{state['generated_questions']}

Conversation History & Tool Outputs:
{state['messages']}

Based on this, what is your reasoning and the single next action to take?
"""
    structured_llm = brain_llm.with_structured_output(BrainThought)
    brain_thought = await structured_llm.ainvoke(prompt)
    print(f"---BRAIN Thought: {brain_thought.reasoning} -> Action: {brain_thought.action}---")
    return {"brain_thought": brain_thought}

async def update_node(state: AgentState) -> dict:
    """Step 4: UPDATE. The results of the action are implicitly added to state by the ToolNode."""
    print("---BRAIN LOOP: Update---")
    # This step is for future logic, like summarizing tool outputs into temp_knowledge.
    # The ToolNode already adds its raw output to 'messages'.
    return {}

async def respond_to_mind_node(state: AgentState) -> dict:
    """The final node, packaging the result for the Mind."""
    print("---BRAIN LOOP: Respond to Mind---")
    return {"messages": [AIMessage(content=state['brain_thought'].tool_input, name="Brain")]}

# --- Conditional Router for the Brain ---

def route_brain_action(state: AgentState) -> str:
    action = state['brain_thought'].action
    if action == 'respond_to_mind':
        return 'respond_to_mind'
    else: # Any of the tool-using actions
        return 'action'

# --- Define and Compile the Brain's Sub-Graph ---

def create_brain_graph():
    workflow = StateGraph(AgentState)
    
    workflow.add_node("generate", generate_node)
    workflow.add_node("think", think_node)
    workflow.add_node("action", brain_tool_node) # 'action' is executing the tool
    workflow.add_node("update", update_node)
    workflow.add_node("respond_to_mind", respond_to_mind_node)
    
    workflow.set_entry_point("generate")
    
    workflow.add_edge("generate", "think")
    
    workflow.add_conditional_edges(
        "think",
        route_brain_action,
        {
            "action": "action",
            "respond_to_mind": "respond_to_mind"
        }
    )
    
    # The crucial loop from your diagram: Action -> Update -> Generate
    workflow.add_edge("action", "update")
    workflow.add_edge("update", "generate")

    workflow.add_edge("respond_to_mind", END)
    
    return workflow.compile()
