# langgraph_cognitive_arch/agent/graphs/brain.py
import json
from typing import List
from langgraph.graph import StateGraph, END
from langchain_core.messages import AIMessage
from pydantic import BaseModel, Field

from agent.state import AgentState, BrainThought, BrainUpdateAction
from agent.logging_config import get_logger
from agent.config import create_llm, update_llm_config, list_llm_configs
from agent.prompts import PROMPTS, update_prompt, list_prompt_keys
from agent.evolution import journal

log = get_logger("brain")

class GeneratedQuestions(BaseModel):
    """A list of questions generated by the Brain to clarify the task."""
    questions: List[str] = Field(description="A list of clarifying questions to break down the main task.")

# --- Nodes for the Brain's Cognitive Loop ---

async def generate_node(state: AgentState) -> dict:
    """Step 1: GENERATE. Generates sub-questions to break down the task."""
    log.info("BRAIN LOOP: Generate")
    prompt = PROMPTS["brain_generate"].format(
        messages=state['messages'],
    )
    llm = create_llm("brain_llm", structured_output_schema=GeneratedQuestions)
    response = await llm.ainvoke(prompt)
    return {"generated_questions": response.questions}


async def think_node(state: AgentState) -> dict:
    """Step 2: THINK. Reviews the generated questions and decides on the next single action."""
    log.info("BRAIN LOOP: Think")
    prompt = PROMPTS["brain_think"].format(
        generated_questions=state['generated_questions'],
        messages=state['messages'],
        llm_configs=list_llm_configs(),
        evolution_summary=journal.summary(limit=10),
    )
    llm = create_llm("brain_llm", structured_output_schema=BrainThought)
    brain_thought = await llm.ainvoke(prompt)
    log.info("BRAIN Thought: %s -> Action: %s", brain_thought.reasoning, brain_thought.action)
    return {"brain_thought": brain_thought}


async def action_node(state: AgentState) -> dict:
    """
    Step 3: ACTION
    Executes the tool chosen by the Brain's think node.
    Handles knowledge access, self-evolution, and journal viewing.
    """
    thought = state["brain_thought"]
    action = thought.action
    tool_input = thought.tool_input or ""

    if action == "access_temp_knowledge":
        log.info("BRAIN ACTION: Accessing Temp Knowledge for key: '%s'", tool_input)
        value = state.get("temp_knowledge", {}).get(
            tool_input,
            f"No value found for key '{tool_input}' in temporary knowledge.",
        )
        result = str(value)

    elif action == "access_permanent_knowledge":
        log.info("BRAIN ACTION: Accessing Permanent Knowledge for query: '%s'", tool_input)
        pk = state.get("permanent_knowledge")
        result = pk.recall_memory(tool_input) if pk else "Permanent knowledge store not available."

    elif action == "write_to_permanent_knowledge":
        log.info("BRAIN ACTION: Writing to Permanent Knowledge: '%s'", tool_input)
        pk = state.get("permanent_knowledge")
        if pk:
            pk.add_memory(tool_input)
            result = f"Successfully wrote '{tool_input}' to permanent knowledge."
        else:
            result = "Permanent knowledge store not available."

    elif action == "evolve_prompt":
        result = _handle_evolve_prompt(tool_input)

    elif action == "evolve_llm_config":
        result = _handle_evolve_llm_config(tool_input)

    elif action == "view_evolution_journal":
        result = _handle_view_journal(tool_input)

    else:
        log.warning("BRAIN ACTION: Unknown action '%s', treating as no-op", action)
        result = f"Unknown action: {action}"

    log.info("BRAIN ACTION result: %s", result[:200])
    return {"messages": [AIMessage(content=result, name="BrainAction")]}


# ── Evolution action helpers ────────────────────────────────────────────────

def _handle_evolve_prompt(tool_input: str) -> str:
    """Parse JSON tool_input and call update_prompt."""
    try:
        data = json.loads(tool_input)
        key = data["key"]
        new_template = data["new_template"]
        reason = data.get("reason", "")
        return update_prompt(key, new_template, reason)
    except (json.JSONDecodeError, KeyError) as e:
        return f"evolve_prompt failed — bad input: {e}. Expected JSON with 'key', 'new_template', 'reason'."
    except ValueError as e:
        return f"evolve_prompt rejected: {e}"


def _handle_evolve_llm_config(tool_input: str) -> str:
    """Parse JSON tool_input and call update_llm_config."""
    try:
        data = json.loads(tool_input)
        key = data["key"]
        model = data.get("model")
        temperature = data.get("temperature")
        reason = data.get("reason", "")
        if model is None and temperature is None:
            return "evolve_llm_config: must specify at least 'model' or 'temperature' to change."
        old, new = update_llm_config(key, model=model, temperature=temperature)
        journal.record("llm_config", key, old, new, reason or "No reason provided")
        return f"LLM config '{key}' updated: {old} → {new}"
    except (json.JSONDecodeError, KeyError) as e:
        return f"evolve_llm_config failed — bad input: {e}. Expected JSON with 'key' and optionally 'model', 'temperature', 'reason'."
    except ValueError as e:
        return f"evolve_llm_config rejected: {e}"


def _handle_view_journal(tool_input: str) -> str:
    """View evolution history with optional filters."""
    limit = 10
    category = None
    if tool_input.strip():
        try:
            data = json.loads(tool_input)
            limit = data.get("limit", 10)
            category = data.get("category")
        except json.JSONDecodeError:
            pass  # just use defaults
    return journal.summary(limit=limit) if not category else "\n".join(
        f"[{e.timestamp[:19]}] {e.category}/{e.key} v{e.version} — {e.reason[:80]}"
        for e in journal.history(category=category, limit=limit)
    ) or "No entries found for that filter."

async def update_node(state: AgentState) -> dict:
    """Step 4: UPDATE. Extract insights from the action result."""
    log.info("BRAIN LOOP: Update")
    
    if not state.get('messages'):
        return {}
        
    last_message = state['messages'][-1]
    prompt = PROMPTS["brain_update"].format(
        temp_knowledge=state.get('temp_knowledge', {}),
        last_message=last_message.content if hasattr(last_message, 'content') else str(last_message),
        editable_prompts=list_prompt_keys(),
    )
    llm = create_llm("brain_update_llm", structured_output_schema=BrainUpdateAction)
    update_action = await llm.ainvoke(prompt)
    
    state_updates = {}

    if update_action.insights:
        log.info("BRAIN Extracted Insights: %s", update_action.insights)
        current_knowledge = state.get('temp_knowledge', {})
        current_knowledge.update(update_action.insights)
        state_updates["temp_knowledge"] = current_knowledge

    # Prompt updates from the update node (passive self-evolution)
    if update_action.prompt_updates:
        for pu in update_action.prompt_updates:
            try:
                result = update_prompt(pu.key, pu.new_template, pu.reason)
                log.info("BRAIN UPDATE SELF-EVOLVE: %s — Reason: %s", result, pu.reason)
            except ValueError as e:
                log.warning("BRAIN UPDATE SELF-EVOLVE rejected: %s", e)

    return state_updates

async def respond_to_mind_node(state: AgentState) -> dict:
    """The final node, packaging the result for the Mind."""
    log.info("BRAIN LOOP: Respond to Mind")
    
    response_content = state['brain_thought'].tool_input
    if not response_content:
        response_content = "I have completed my reasoning but did not formulate a specific response."
        
    return {"messages": [AIMessage(content=response_content, name="Brain")]}

# --- Conditional Router for the Brain ---

def route_brain_action(state: AgentState) -> str:
    action = state['brain_thought'].action
    if action == 'respond_to_mind':
        return 'respond_to_mind'
    else: # Any of the tool-using actions
        return 'action'

# --- Define and Compile the Brain's Sub-Graph ---

def create_brain_graph():
    workflow = StateGraph(AgentState)
    
    workflow.add_node("generate", generate_node)
    workflow.add_node("think", think_node)
    workflow.add_node("action", action_node)  # custom node with state access
    workflow.add_node("update", update_node)
    workflow.add_node("respond_to_mind", respond_to_mind_node)
    
    workflow.set_entry_point("generate")
    
    workflow.add_edge("generate", "think")
    
    workflow.add_conditional_edges(
        "think",
        route_brain_action,
        {
            "action": "action",
            "respond_to_mind": "respond_to_mind"
        }
    )
    
    # The crucial loop from your diagram: Action -> Update -> Generate
    workflow.add_edge("action", "update")
    workflow.add_edge("update", "generate")

    workflow.add_edge("respond_to_mind", END)
    
    return workflow.compile()
